name: Create and publish Docker image

on:
  push:
    branches: ['main']
    paths-ignore:
      - LICENSE
      - README.md
      - .gitignore

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "docker-hub-publish"
  cancel-in-progress: true

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          pull: true
          tags: econumo/econumo-one-frontend:latest