name: Create and publish Docker image

on:
  push:
    branches: ['main']
    paths-ignore:
      - LICENSE
      - README.md
      - .gitignore

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: "docker-publish"
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          pull: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest